/*
 * Copyright (C) 2011 Flamingo Project (http://www.cloudine.io).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
Ext.define('Flamingo2.view.designer.nodeList.NodeListModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.nodeListModel',

    stores: {
        nodemeta: {
            model: 'Flamingo2.model.designer.NodeMeta',

            data: [ // TODO description 다국어 처리
                {
                    "type": "OTHERS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-condition-if.png",
                    "identifier": "BPMN_INCLUSIVE_FORK",
                    "name": message.msg('workflow.common.inclusive.fork'),
                    "qualifierLabel": "inclusive_fork",
                    "description": message.msg('workflow.common.inclusive.fork'),
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "END",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "OTHERS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-condition-end.png",
                    "identifier": "BPMN_INCLUSIVE_JOIN",
                    "name": message.msg('workflow.common.inclusive.join'),
                    "qualifierLabel": "inclusive_join",
                    "description": message.msg('workflow.common.inclusive.join'),
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "END",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "OTHERS",
                    "icon": CONSTANTS.CONTEXT_PATH + '/resources/images/icons/workflow/workflow-pararell-process.png',
                    "identifier": "BPMN_PARALLEL",
                    "name": message.msg('workflow.common.pararell.join'),
                    "qualifierLabel": "parallel",
                    "description": message.msg('workflow.common.pararell.join'),
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "OTHERS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-pararell-end.png",
                    "identifier": "BPMN_JOIN",
                    "name": message.msg('workflow.common.pararell.fork'),
                    "qualifierLabel": "join",
                    "description": message.msg('workflow.common.pararell.fork'),
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "END",
                    "notAllowedNextNodes": ""
                },
                /*
                 {
                 "type": "OTHERS",
                 "icon": CONSTANTS.CONTEXT_PATH + '/resources/images/icons/workflow/workflow-sub.png',
                 "identifier": "SUBPROCESS",
                 "name": message.msg('workflow.common.subflow'),
                 "qualifierLabel": "subprocess",
                 "description": message.msg('workflow.common.subflow'),
                 "isCheckColumns": false,
                 "fixedInputColumns": false,
                 "fixedOutputColumns": false,
                 "readOnlyOutputColumns": false,
                 "ignoreInput": true,
                 "ignoreOutput": true,
                 "minPrevNodeCounts": 0,
                 "maxPrevNodeCounts": -1,
                 "minNextNodeCounts": 0,
                 "maxNextNodeCounts": -1,
                 "notAllowedPrevTypes": "",
                 "notAllowedNextTypes": "",
                 "notAllowedPrevNodes": "",
                 "notAllowedNextNodes": ""
                 },
                 */
                {
                    "type": "HADOOP",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mapreduce.png",
                    "identifier": "HADOOP_MR",
                    "name": message.msg('workflow.common.mapreduce'),
                    "qualifierLabel": "mr",
                    "description": message.msg('workflow.common.mapreduce'),
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "HADOOP",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-pig.png",
                    "identifier": "HADOOP_PIG",
                    "name": message.msg('workflow.common.pig'),
                    "qualifierLabel": "pig",
                    "description": message.msg('workflow.common.pig'),
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": 1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "HADOOP",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-hive.png",
                    "identifier": "HADOOP_HIVE",
                    "name": message.msg('workflow.common.hive'),
                    "qualifierLabel": "hive",
                    "description": message.msg('workflow.common.hive'),
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "INMEMORY",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-spark.png",
                    "identifier": "HADOOP_SPARK",
                    "name": message.msg('workflow.common.spark'),
                    "qualifierLabel": "mr",
                    "description": message.msg('workflow.common.spark'),
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "HADOOP",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-java.png",
                    "identifier": "HADOOP_JAVA",
                    "name": message.msg('workflow.common.java'),
                    "qualifierLabel": "java",
                    "description": message.msg('workflow.common.java'),
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "HADOOP",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-java.png",
//                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-import.png",
                    "identifier": "HADOOP_SQOOP_IMPORT",
                    "name": message.msg('workflow.common.sqoop.import'),
                    "qualifierLabel": "si",
                    "description": message.msg('workflow.common.sqoop.import'),
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "HADOOP",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-java.png",
//                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-export.png",
                    "identifier": "HADOOP_SQOOP_EXPORT",
                    "name": message.msg('workflow.common.sqoop.export'),
                    "qualifierLabel": "so",
                    "description": message.msg('workflow.common.sqoop.export'),
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "OTHERS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-shell.png",
                    "identifier": "HADOOP_SHELL",
                    "name": message.msg('workflow.common.shell'),
                    "qualifierLabel": "shell",
                    "description": message.msg('workflow.common.shell'),
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "OTHERS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-r.png",
                    "identifier": "HADOOP_R",
                    "name": message.msg('workflow.common.r'),
                    "qualifierLabel": "R",
                    "description": message.msg('workflow.common.r'),
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "OTHERS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-python.png",
                    "identifier": "HADOOP_PYTHON",
                    "name": message.msg('workflow.common.python'),
                    "qualifierLabel": "python",
                    "description": message.msg('workflow.common.python'),
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 1,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 1,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "STATISTICS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-statistics.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_NUMERIC_STATISTICS",
                    "name": "Numeric Statistics Distribution",
                    "qualifierLabel": "anumstat",
                    "description": "Numeric Statistics Distribution",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "STATISTICS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-statistics.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_NOMINAL_STATISTICS",
                    "name": "Nominal Statistics Distribution",
                    "qualifierLabel": "nominal",
                    "description": "Nominal Statistics Distribution",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "STATISTICS",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-statistics.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CERTAIN_FACTOR_SUM",
                    "name": "Certainty Factor based Sum",
                    "qualifierLabel": "acfs",
                    "description": "Certainty Factor based Sum",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_NORMAL",
                    "name": "Min/Max Normalization",
                    "qualifierLabel": "anormal",
                    "description": "Min/Max Normalization",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "ETL",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ETL_CHAR_REMOVER",
                    "name": "Remove Characters",
                    "qualifierLabel": "remove_chars",
                    "description": "Remove Characters",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                /*
                 {
                 "type": "ETL",
                 "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                 "jobType": "MAPREDUCE",
                 "identifier": "ETL_APACHE_ACCESS",
                 "name": "Apache Access To CSV",
                 "qualifierLabel": "apache_access",
                 "description": "Apache Access To CSV",
                 "isCheckColumns": false,
                 "fixedInputColumns": false,
                 "fixedOutputColumns": false,
                 "readOnlyOutputColumns": false,
                 "ignoreInput": true,
                 "ignoreOutput": true,
                 "minPrevNodeCounts": 0,
                 "maxPrevNodeCounts": -1,
                 "minNextNodeCounts": 0,
                 "maxNextNodeCounts": -1,
                 "notAllowedPrevTypes": "",
                 "notAllowedNextTypes": "",
                 "notAllowedPrevNodes": "",
                 "notAllowedNextNodes": ""
                 },
                 */
                /*
                 {
                 "type": "ETL",
                 "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                 "jobType": "MAPREDUCE",
                 "identifier": "ETL_UIMA_SEQ",
                 "name": "UIMA To Sequence File",
                 "qualifierLabel": "uima_seq",
                 "description": "UIMA To Sequence File",
                 "isCheckColumns": false,
                 "fixedInputColumns": false,
                 "fixedOutputColumns": false,
                 "readOnlyOutputColumns": false,
                 "ignoreInput": true,
                 "ignoreOutput": true,
                 "minPrevNodeCounts": 0,
                 "maxPrevNodeCounts": -1,
                 "minNextNodeCounts": 0,
                 "maxNextNodeCounts": -1,
                 "notAllowedPrevTypes": "",
                 "notAllowedNextTypes": "",
                 "notAllowedPrevNodes": "",
                 "notAllowedNextNodes": ""
                 },
                 */
                /*
                 {
                 "type": "ETL",
                 "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-etl.png",
                 "jobType": "MAPREDUCE",
                 "identifier": "ETL_UIMA_APP",
                 "name": "UIMA Application",
                 "qualifierLabel": "uima_app",
                 "description": "UIMA Application",
                 "isCheckColumns": false,
                 "fixedInputColumns": false,
                 "fixedOutputColumns": false,
                 "readOnlyOutputColumns": false,
                 "ignoreInput": true,
                 "ignoreOutput": true,
                 "minPrevNodeCounts": 0,
                 "maxPrevNodeCounts": -1,
                 "minNextNodeCounts": 0,
                 "maxNextNodeCounts": -1,
                 "notAllowedPrevTypes": "",
                 "notAllowedNextTypes": "",
                 "notAllowedPrevNodes": "",
                 "notAllowedNextNodes": ""
                 },
                 */
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CORR_BOOL",
                    "name": "Boolean Similarity/Correlation",
                    "qualifierLabel": "acorrb",
                    "description": "Boolean Similarity/Correlation",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CORR_NUMERIC",
                    "name": "Numeric Similarity/Correlation",
                    "qualifierLabel": "acorrn",
                    "description": "Numeric Similarity/Correlation",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CORR_STRING",
                    "name": "String Similarity",
                    "qualifierLabel": "acorrs",
                    "description": "String Similarity",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_ID3",
                    "name": "ID3 Classification",
                    "qualifierLabel": "aid3",
                    "description": "ID3 Classification",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },

                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_KMEANS",
                    "name": "K-Means Clustering",
                    "qualifierLabel": "akmeans",
                    "description": "K-Means based Clustering",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_EM",
                    "name": "EM Clustering",
                    "qualifierLabel": "aem",
                    "description": "EM based Clustering",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CF_SIM",
                    "name": "CF based Similarity",
                    "qualifierLabel": "acfsim",
                    "description": "Collaborative Filtering based Similarity",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CONTENT_SIM",
                    "name": "Content based Similarity",
                    "qualifierLabel": "aconsim",
                    "description": "Content based Similarity",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CF_USER_RECOMMEND",
                    "name": "User Similarity based Recommendation",
                    "qualifierLabel": "auserrec",
                    "description": "Collaborative Filtering User based Recommendation",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MINING",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mining.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_ANKUS_CF_ITEM_RECOMMEND",
                    "name": "Item Similarity based Recommendation",
                    "qualifierLabel": "aitemrec",
                    "description": "Collaborative Filtering Item based Recommendation",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_CF_ITEM",
                    "name": "Item-Based Collaborative Filtering",
                    "qualifierLabel": "mahoutitemrec",
                    "description": "Item-Based Collaborative Filtering",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_MATRIX_FACT_ALS",
                    "name": "Factorized Recommendation",
                    "qualifierLabel": "mahoutmatrixfact",
                    "description": "Factorized Recommendation",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_PARALLEL_ALS",
                    "name": "Parallel ALS",
                    "qualifierLabel": "mahoutparallelals",
                    "description": "Parallel ALS",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_KMEANS",
                    "name": "k-Means Clustering",
                    "qualifierLabel": "mahoutkmeans",
                    "description": "k-Means Clustering",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_FUZZY_K_MEANS",
                    "name": "Fuzzy k-Means Clustering",
                    "qualifierLabel": "mahoutfuzzykmeans",
                    "description": "Fuzzy k-Means Clustering",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_STREAMING_K_MEANS",
                    "name": "Streaming k-Means Clustering",
                    "qualifierLabel": "mahoutstreamingkmeans",
                    "description": "Streaming k-Means Clustering",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_QUALCLUSTER",
                    "name": "Cluster Quality Summarizer",
                    "qualifierLabel": "Mahout Cluster Quality Summarizer",
                    "description": "Mahout Cluster Quality Summarizer",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_SEQ2SPARSE",
                    "name": "Sequence File To Sparse Vector",
                    "qualifierLabel": "mahoutseq2sparse",
                    "description": "Sequence File to Sparse Vector",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_SPECTRAL_K_MEANS",
                    "name": "Spectral k-Means Clustering",
                    "qualifierLabel": "mahoutspectralkmeans",
                    "description": "Spectral k-Means Clustering",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_CLUSTER_DUMP",
                    "name": "Cluster Dump",
                    "qualifierLabel": "mahout cluser dump",
                    "description": "Cluster Dump",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_SEQDIRECTORY",
                    "name": "To Sequence File",
                    "qualifierLabel": "Mahout Seqdirectory",
                    "description": "To Sequence File",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_TRAINNB",
                    "name": "Train Naive Bayes / CNaive Bayes",
                    "qualifierLabel": "mahouttrainnb",
                    "description": "Train Naive Bayes / CNaive Bayes",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                },
                {
                    "type": "MAHOUT",
                    "icon": CONSTANTS.CONTEXT_PATH + "/resources/images/icons/workflow/workflow-mahout.png",
                    "jobType": "MAPREDUCE",
                    "identifier": "ALG_MAHOUT_TESTNB",
                    "name": "Test Naive Bayes / CNaive Bayes",
                    "qualifierLabel": "mahouttestnb",
                    "description": "Test Naive Bayes / CNaive Bayes",
                    "isCheckColumns": false,
                    "fixedInputColumns": false,
                    "fixedOutputColumns": false,
                    "readOnlyOutputColumns": false,
                    "ignoreInput": true,
                    "ignoreOutput": true,
                    "minPrevNodeCounts": 0,
                    "maxPrevNodeCounts": -1,
                    "minNextNodeCounts": 0,
                    "maxNextNodeCounts": -1,
                    "notAllowedPrevTypes": "",
                    "notAllowedNextTypes": "",
                    "notAllowedPrevNodes": "",
                    "notAllowedNextNodes": ""
                }
            ]
        }
    }
});